### ISSUE TITLE
RSSI level

### ISSUE THREAD

**Issue by MiloshCZ** [abouillot/HomeAutomation#14] opened 2015-06-24 15:41 UTC
Hi,
thank you for porting RFM69 library from arduino to RaspPi. But I have small issue. Gateway sometimes (about 1 from 5) reports RSSI level "0". Other values are received OK.

Next question is about RSSI level. At arduino gateway, I have RSSI level about -34dBm, but at RaspPi I have RSSI level about -90dBm. I have tried add capacitor (68uF tantalum) to power supply of RFM69 module, but no change.

**Comment by abouillot** [comment] 2015-06-24 16:07
I noticed similar results, without ideas on the root cause. It might be related to timing, as the RSSI, as it it read from the module at the end of the packet retrieval. By moving it at the beginning of the interrupt handler (~line 426), the values are much higher (-38/-76 in my case). However, this would require more testing to avoid other side effects.

Regarding the 0 value, I think this was due to the use of the latest RSSI, rather than the one coming with the packet. I've made a fix for this, just committed

**Closed as completed** 2015-12-02 17:00 UTC
